// <auto-generated />
using System;
using Doclyn.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Doclyn.Infrastructure.Database.Migrations
{
    [DbContext(typeof(DoclynDbContext))]
    [Migration("20260617014409_AddDocumentClassIndexers")]
    partial class AddDocumentClassIndexers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Doclyn.Domain.Entities.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("DocumentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("DOCUMENT_STATUS");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("DOCUMENT_TYPE");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("FILE_HASH");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("FILE_NAME");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("PROCESSED_AT");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("STORAGE_PATH");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UPDATED_AT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("USER_ID");

                    b.HasKey("Id")
                        .HasName("PK_DOCUMENTS");

                    b.HasIndex("UserId", "DocumentStatus", "DocumentType", "CreatedAt")
                        .HasDatabaseName("IX_DOCUMENTS_USER_ID_DOCUMENT_STATUS_DOCUMENT_TYPE_CREATED_AT");

                    b.ToTable("DOCUMENTS");
                });

            modelBuilder.Entity("Doclyn.Domain.Entities.DocumentClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("DISPLAY_NAME");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("GROUP_NAME");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<bool>("IsSystemDefined")
                        .HasColumnType("boolean")
                        .HasColumnName("IS_SYSTEM_DEFINED");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("NAME");

                    b.Property<string>("SubGroup")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("SUB_GROUP");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UPDATED_AT");

                    b.HasKey("Id")
                        .HasName("PK_DOCUMENT_CLASSES");

                    b.HasIndex("Group")
                        .HasDatabaseName("IX_DOCUMENT_CLASSES_GROUP_NAME");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_DOCUMENT_CLASSES_IS_ACTIVE");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_DOCUMENT_CLASSES_NAME");

                    b.HasIndex("SubGroup")
                        .HasDatabaseName("IX_DOCUMENT_CLASSES_SUB_GROUP");

                    b.ToTable("DOCUMENT_CLASSES");
                });

            modelBuilder.Entity("Doclyn.Domain.Entities.DocumentClassExample", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ID");

                    b.Property<decimal>("Confidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("CONFIDENCE");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CREATED_AT");

                    b.Property<Guid>("DocumentClassId")
                        .HasColumnType("uuid")
                        .HasColumnName("DOCUMENT_CLASS_ID");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("DOCUMENT_ID");

                    b.HasKey("Id")
                        .HasName("PK_DOCUMENT_CLASS_EXAMPLES");

                    b.HasIndex("DocumentClassId")
                        .HasDatabaseName("IX_DOCUMENT_CLASS_EXAMPLES_DOCUMENT_CLASS_ID");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("IX_DOCUMENT_CLASS_EXAMPLES_DOCUMENT_ID");

                    b.ToTable("DOCUMENT_CLASS_EXAMPLES");
                });

            modelBuilder.Entity("Doclyn.Domain.Entities.DocumentClassIndexer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CREATED_AT");

                    b.Property<int>("DataType")
                        .HasColumnType("integer")
                        .HasColumnName("DATA_TYPE");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("DISPLAY_NAME");

                    b.Property<Guid>("DocumentClassId")
                        .HasColumnType("uuid")
                        .HasColumnName("DOCUMENT_CLASS_ID");

                    b.Property<string>("ExtractionHint")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("EXTRACTION_HINT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<bool>("IsMultiple")
                        .HasColumnType("boolean")
                        .HasColumnName("IS_MULTIPLE");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("IS_REQUIRED");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("NAME");

                    b.Property<string>("RegexPattern")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("REGEX_PATTERN");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UPDATED_AT");

                    b.HasKey("Id")
                        .HasName("PK_DOCUMENT_CLASS_INDEXERS");

                    b.HasIndex("DocumentClassId")
                        .HasDatabaseName("IX_DOCUMENT_CLASS_INDEXERS_DOCUMENT_CLASS_ID");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_DOCUMENT_CLASS_INDEXERS_IS_ACTIVE");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_DOCUMENT_CLASS_INDEXERS_NAME");

                    b.HasIndex("DocumentClassId", "Name", "IsActive")
                        .IsUnique()
                        .HasDatabaseName("IX_DOCUMENT_CLASS_INDEXERS_DOCUMENT_CLASS_ID_NAME_IS_ACTIVE");

                    b.ToTable("DOCUMENT_CLASS_INDEXERS");
                });

            modelBuilder.Entity("Doclyn.Domain.Entities.ExtractedData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("DATA");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("DOCUMENT_ID");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UPDATED_AT");

                    b.HasKey("Id")
                        .HasName("PK_EXTRACTED_DATA");

                    b.HasIndex("DocumentId")
                        .IsUnique()
                        .HasDatabaseName("IX_EXTRACTED_DATA_DOCUMENT_ID");

                    b.ToTable("EXTRACTED_DATA");
                });

            modelBuilder.Entity("Doclyn.Domain.Entities.PasswordResetRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ID");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("ATTEMPTS");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("CODE_HASH");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CREATED_AT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("EXPIRES_AT");

                    b.Property<bool>("IsResetTokenUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("IS_RESET_TOKEN_USED");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("IS_USED");

                    b.Property<DateTime?>("ResetTokenExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("RESET_TOKEN_EXPIRES_AT");

                    b.Property<string>("ResetTokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("RESET_TOKEN_HASH");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UPDATED_AT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("USER_ID");

                    b.HasKey("Id")
                        .HasName("PK_PASSWORD_RESET_REQUESTS");

                    b.HasIndex("ResetTokenHash")
                        .IsUnique()
                        .HasDatabaseName("IX_PASSWORD_RESET_REQUESTS_RESET_TOKEN_HASH")
                        .HasFilter("\"RESET_TOKEN_HASH\" <> ''");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_PASSWORD_RESET_REQUESTS_USER_ID");

                    b.ToTable("PASSWORD_RESET_REQUESTS");
                });

            modelBuilder.Entity("Doclyn.Domain.Entities.ProcessingLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CREATED_AT");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("DOCUMENT_ID");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("MESSAGE");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("STATUS");

                    b.Property<string>("Step")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("STEP");

                    b.HasKey("Id")
                        .HasName("PK_PROCESSING_LOGS");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("IX_PROCESSING_LOGS_DOCUMENT_ID");

                    b.ToTable("PROCESSING_LOGS");
                });

            modelBuilder.Entity("Doclyn.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CREATED_AT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("EXPIRES_AT");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("REPLACED_BY_TOKEN_HASH");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("REVOKED_AT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("TOKEN_HASH");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UPDATED_AT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("USER_ID");

                    b.HasKey("Id")
                        .HasName("PK_REFRESH_TOKENS");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_REFRESH_TOKENS_EXPIRES_AT");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("IX_REFRESH_TOKENS_TOKEN_HASH");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_REFRESH_TOKENS_USER_ID");

                    b.ToTable("REFRESH_TOKENS");
                });

            modelBuilder.Entity("Doclyn.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("EMAIL");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("NAME");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("PASSWORD_HASH");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ROLE");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UPDATED_AT");

                    b.HasKey("Id")
                        .HasName("PK_USERS");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_USERS_EMAIL");

                    b.ToTable("USERS");
                });

            modelBuilder.Entity("Doclyn.Domain.Entities.Document", b =>
                {
                    b.HasOne("Doclyn.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DOCUMENTS__USERS_USER_ID");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Doclyn.Domain.Entities.DocumentClassExample", b =>
                {
                    b.HasOne("Doclyn.Domain.Entities.DocumentClass", "DocumentClass")
                        .WithMany()
                        .HasForeignKey("DocumentClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DOCUMENT_CLASS_EXAMPLES_DOCUMENT_CLASSES_DOCUMENT_CLASS_ID");

                    b.HasOne("Doclyn.Domain.Entities.Document", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DOCUMENT_CLASS_EXAMPLES_DOCUMENTS_DOCUMENT_ID");

                    b.Navigation("Document");

                    b.Navigation("DocumentClass");
                });

            modelBuilder.Entity("Doclyn.Domain.Entities.DocumentClassIndexer", b =>
                {
                    b.HasOne("Doclyn.Domain.Entities.DocumentClass", "DocumentClass")
                        .WithMany("Indexers")
                        .HasForeignKey("DocumentClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DOCUMENT_CLASS_INDEXERS_DOCUMENT_CLASSES_DOCUMENT_CLASS_ID");

                    b.Navigation("DocumentClass");
                });

            modelBuilder.Entity("Doclyn.Domain.Entities.ExtractedData", b =>
                {
                    b.HasOne("Doclyn.Domain.Entities.Document", "Document")
                        .WithOne()
                        .HasForeignKey("Doclyn.Domain.Entities.ExtractedData", "DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_EXTRACTED_DATA_DOCUMENTS_DOCUMENT_ID");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("Doclyn.Domain.Entities.PasswordResetRequest", b =>
                {
                    b.HasOne("Doclyn.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PASSWORD_RESET_REQUESTS__USERS_USER_ID");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Doclyn.Domain.Entities.ProcessingLog", b =>
                {
                    b.HasOne("Doclyn.Domain.Entities.Document", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PROCESSING_LOGS_DOCUMENTS_DOCUMENT_ID");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("Doclyn.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Doclyn.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_REFRESH_TOKENS__USERS_USER_ID");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Doclyn.Domain.Entities.DocumentClass", b =>
                {
                    b.Navigation("Indexers");
                });
#pragma warning restore 612, 618
        }
    }
}
